services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mariadb  
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=senha_root
      - DB_NAME=chatdb
    networks:
      - chatnet

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=senha_root
      - MYSQL_DATABASE=chatdb
    volumes:
      - mariadb-data:/var/lib/mysql  
    networks:
      - chatnet

volumes:
  mariadb-data:

networks:
  chatnet:
    driver: bridge
